# Generated by Django 5.2.9 on 2025-12-12 19:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_seed_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["id"],
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-first_line", "id"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="cart_snapshot",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Состав заказа (слепок)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(default="RUB", max_length=3, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="order",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="Метаданные"),
        ),
        migrations.AlterField(
            model_name="order",
            name="notified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Уведомлено продавцов"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, verbose_name="ID платежа"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Создан"),
                    ("awaiting_confirmation", "Ожидает подтверждения"),
                    ("paid", "Оплачен"),
                    ("failed", "Ошибка"),
                    ("canceled", "Отменен"),
                ],
                default="pending",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Сумма",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="store.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=255, verbose_name="Название товара"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="details",
            field=models.JSONField(blank=True, default=list, verbose_name="Детали"),
        ),
        migrations.AlterField(
            model_name="product",
            name="first_line",
            field=models.BooleanField(default=True, verbose_name="Первая линия"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_path",
            field=models.CharField(max_length=255, verbose_name="Путь к изображению"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="store.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
    ]
